# Это файл с секретами (НИКОМУ НЕ ПОКАЗЫВАЙТЕ!)
[destination.postgres.credentials]
database = "document_analytics"
username = "analyzer"
password = "secure_password_42"
host = "localhost"
port = 5432
connect_timeout = 15
sslmode = "disable"